### ISSUE TITLE
support smart-compile

### ISSUE THREAD

**Issue by tjaartvdwalt** [jorgenschaefer/emacs-tdd#2]
Would it be easy to to add [smart-compile](https://www.emacswiki.org/emacs/SmartCompile) support for emacs-tdd?

**Comment by jorgenschaefer** [comment]
Try setting `tdd-test-function` to `smart-compile`?

**Comment by tjaartvdwalt** [comment]
Thanks for the reply!

For anybody else that might be interested the following works for me:

```elisp
    (custom-set-variables
     '(tdd-test-function (smart-compile)))
```
